### PR TITLE
Fixes Chris Coyier's name

### PR DESCRIPTION
**Pull request by zendy**
Change from Coyer -> Coyier

### CODE REVIEW

**Comment by gr2m** [comment]
Oh my, thanks @zendy!

**Comment by zendy** [comment]
No worries @gr2m, just that I'm a bit of Chris Coyier fanboy lol

**Comment by gr2m** [comment]
so am I, thanks for keeping me to embarrass myself ;-)

**Comment by zendy** [comment]
I don't know what are you talking about man _wink_ :)

btw I really like your talk on `no backend`, we are planning to create an app, but I'm not that good with backend, so that talk kind of  open my eyes. I've read about `Hoodie` before, but don't fully understand it yet. If it's possible, in the future can I ask you questions or suggestions about `Hoodie` or `no backend` in general?

**Comment by gr2m** [comment]
Sure, I'm happy to help

**Comment by zendy** [comment]
Thanks, I want to discuss and ask questions about `nobackend` concept if it's possible. Can I email you to ask questions? I can only see your twitter account in your `github` profile.

**Comment by zendy** [comment]
I have few questions:
1. `nobackend` doesn't mean that no backend is used at all right? Does that mean that it's a backend that's easier to use?
1. In the future, will `Hoodie` can be customised to use other `noSQL` database? Such as `mongo` etc?

**Comment by gr2m** [comment]
Yes, exactly. I'm working on an update for the website that will make it more clear I hope: gr2m.github.com/nobackend.org – Let me know what you think. I've also added a blog.

Regarding Hoodie: in theory, you could use Hoodie with every kind of backend, even with relational databases. All that needs to be done is to create a hoodie.js adapter, that provides the same API as the current Hoodie. If you want to work on that, let me know, that'd be quite cool actually

**Comment by zendy** [comment]
So in a sense, the actual server side backend is an `api` that we access through frontend code? We abstracted that `api` in a way to make it very easy to access from the frontend?

Awesome..I really want to give `hoodie` a try now..I need to allocate some free time to play with it :)
I'd like to give a try with other type of databases, though I'd need some guidance. I know a bit about backend, but not that great. Maybe you'd be able to give me some guidance later on?

**Comment by gr2m** [comment]
sure, I'll help as good as I can

**Comment by zendy** [comment]
thanks man! So, do I start from https://github.com/hoodiehq/my-first-hoodie?

btw if you are okay with it, would you mind to email me on my email address, you can find it https://github.com/zendy? So it'll be easier if I need some guidance?

**Comment by gr2m** [comment]
Just follow the instructions on http://hood.ie. if you gave any trouble, just open up issues
—
Gregor Martynus

**Pull request merged**
