### PR TITLE
added Sockethub!

### PR DESCRIPTION
**Pull request by silverbucket**

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks Nick, @xmartin and @skddc already mentioned Sockethub several times as an supplement for remoteStorage to allow things like sending emails and other backend tasks. I've looked on the page and in the README but can't figure out yet how it works, exactly? Especially from a frontend developer perspective, how can I use it (in terms of JavaScript Code) to accomplish what kind of tasks, exactly? Could you elaborate?

**Comment by silverbucket** [comment]
Hi Gregor,  yeah I think we could still use some better documentation to explain the concept. :)

The basic idea is that you write your app to carry out it's messaging via a Sockethub server, that sockethub server can be defined by the user. Similar to how the user tells the app where their remoteStorage account is.

At that point, the app uses JSON objects (loosely based on Activity Streams) through the websocket indicating it's intent. Using the same basic JSON objects, it can indicate various platforms (XMPP, Facebook, Twitter, Email, etc. etc.) and verbs ('send'. 'follow', 'update', 'make-friend', etc.) target(s) (address) etc.

For an idea of the basic overview see this page (still needs work):
https://github.com/sockethub/sockethub/blob/master/doc/architecture_overview.md

And for an idea of what the Activity Stream objects look like (work in progress) see here:
https://github.com/sockethub/sockethub/blob/master/doc/misc/api_protocol.txt

This is essentially what we are referring to as the polyglot approach. Using a generic set of JSON objects, you can write an app to make use of any platform sockethub supports (many are planned, but help would increase the rate in which was can write them - for example I'm current head deep in XMPP and it will take a while to get it right). 

For an example app, check out Dogtalk:
https://github.com/sockethub/dogtalk

It's very much under development and changes daily, right now you can send and receive messages via. XMPP, but the idea is that it would be trivial to add support for facebook and twitter or irc as well. So, in the end, my goal is to make this a full featured, unhosted, chat app. IRC, XMPP being my first goals, adding twitter and facebook in (though it's mostly a question of how to design the UI to properly represent these things, rather than how to implement each protocol in the app, which IMO is a good problem).

I hope this helps, and if you have any ideas or suggestions, ciritique PLEASE let me know. This is still very much a new project and the more eyeballs and brains on it the better. :)

**Comment by gr2m** [comment]
That's awesome Nick! I'll definitely look into it, I just have to catch up with tons of mails and other shizzle after all the travel of the past weeks.

Let's leave the pull request open and keep discussing until we add it to nobackend.org. I think right now it's a bit to hard to understand, but I'm happy to help with feedback to help on that. I'll get back to you as soon as I had the chance to play with it myself, is that okay?

**Comment by silverbucket** [comment]
Sure, just keep in mind it's very much in a pre-alpha state, so you may encounter bugs :) 

If you want to chat while you try it out you can try to get me on freenode.net in the #sockethub channel (Im slvrbckt on there). If I'm away maybe others will be around to answer questions

**Comment by gr2m** [comment]
will do, thanks Nick!

**Comment by silverbucket** [comment]
Hi Gregor, did you get a chance to evaluate Sockethub? Is there something specific that made you decide to reject the pull request?

**Comment by gr2m** [comment]
oh damn, that was by accident, didn't meant to reject it, wanted to leave it open, so sorry!!!
Do you know if I can reopen it? Don't see a button ... I'm so sorry, that's a bit embarrassing

**Comment by gr2m** [comment]
I was able to reopen your pull request :-)

So hey @silverbucket, do you think we could add an implementation to the [example invoicing app](https://github.com/noBackend/example-invoice) with remoteStorage/socketHub? Or to add another example app where the backend is somewhat abstracted away, so we can add other implementations to it?

**Comment by silverbucket** [comment]
Hi Gregor, where Sockethub focuses on is messaging, it's not a data store,
so I don't think an invoicing app would make sense for it. We are working
on a messaging app, Dogtalk, http://github.com/sockethub/dogtalk

The backend is completely abstracted away, using simple JSON activity
streams to communicate. And the backend service can live anywhere, you can
point the app to it.

**Comment by gr2m** [comment]
Okay, I thought you could use remoteStorage for data store, and Sockethub for the backend tasks, like sending email? Or is that out of scope for SocketHub?

But if it's not a good fit at the moment doesn't mean we shouldn't add it at some point. 

But we should do an implementation of the example app with remoteStorage anyway. It won't have support for the file conversion or sending emails, but that's not a big problem. Would you like to take acton on that?

**Comment by raucao** [comment]
There's TodoMVC for that, and we have remoteStorage versions of it.

**Comment by gr2m** [comment]
@skddc feel free to add that to the set of example apps. Only requirement would be that the backend implementation is abstracted, so we can add an implementation with another noBackend solution and compare the implementations easily

**Comment by silverbucket** [comment]
Re: Email - yes, Sockethub can send emails. SMTP is already implemented and
we're planning POP and IMAP at some point after we finish work on XMPP and
other chat related functionality.

Do you mean that we wouldn't be able to get Sockethub listed until it was
part of an invoice demo app? We're really busy building other aspects of
Sockethub and Dogtalk so I personally don't really have any time to take on
other demo apps at the moment.

**Comment by gr2m** [comment]
That's great, so technically it would be possible? I'm happy to help with that, so maybe we could collaborate? Maybe do a few hours pairing some day the coming week? What you think?

**Comment by silverbucket** [comment]
Sure, we could do something like that this week. Although I've been in
Berlin this week, I leave back to Prague tomorrow, but we could meet up on
IRC or something. I'm always on irc.freenode.net #sockethub

Right now there's not a public Sockethub instance available for use,
because we don't have a public release. But we can do the development with
Sockethub running as a local instance.

**Comment by gr2m** [comment]
cool! Let's just give it a try for 2 hours and see how it goes? How does Wednesday or Thursday look like on your side? I've no appointments yet

**Comment by silverbucket** [comment]
Any chance we can get this merged now? (it's closed again)

**Comment by gr2m** [comment]
sorry, was not intentional again, so sorry :-(
And yes, I'll add SocketHub to the new website at http://gr2m.github.io/nobackend.org/solutions.html

**Comment by silverbucket** [comment]
cool :)

**Pull request closed without merging**
