### PR TITLE
Update solutions.html

### PR DESCRIPTION
**Pull request by jcrubino**
add staticapps.org to the solutions page

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks for the pull request? What is "flat app design" though? Is this about design or architecture?

**Comment by jcrubino** [comment]
Architecture... sorry it is a mincing of words.

"flat" was meant to convey that the architecture does not need to be a big pile of servers.

The world is flat, in design flat is working.... so why not the architecture??

**Comment by gr2m** [comment]
I fear that using flat might be very confusing for frontend people, wich I consider the main target group of noBacked. But yeah noBackend itself is confusing, too ;)

What's your relation to staticapps.org? How about a quick skype chat on all the things? I'd love to hear your general opinion on noBackend and the related projects.

**Comment by jcrubino** [comment]
@gr2m None.  I had come across the nobackend while researching for a project a few months ago and then I saw the staticapps.com on one of the programmer forums.  There is definitely momentum building for static sites and apps with low to zero infrastructure.

**Comment by mbleigh** [comment]
@gr2m I wrote everything on staticapps.org, happy to chat. Let's set something up! (my email's on my GH profile)

**Comment by gr2m** [comment]
I've added staticapps.org to http://nobackend.org/solutions.html

**Pull request closed without merging**
