### PR TITLE
Adding Moovweb to the solutions list & an example on how to use it.

### PR DESCRIPTION
**Pull request by ptrikutam**

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks Pavan! I'm travelling at the moment, sorry to let you wait. I'll look into it over the weekend. 
I quickly looked at moovweb.com and tried to find a JavaScript API that frontend developers can use to build noBackend apps. Do you have something like that? If yes, could you point me to some docs or code that I could look into?

**Comment by ptrikutam** [comment]
Our technology allows you to build apps as they wish. They can choose to use JavaScript, HTML5, CSS, and any other technologies they prefer.

Here's some documentation on building mobile websites (using only front end tools) using our SDK: https://console.moovweb.com/learn/training/index. These documents cover transforming an existing site into a mobile site.

And following that, here's some further documentation on how to create an app from that base (in our example, we use PhoneGap): https://console.moovweb.com/learn/training/building_a_site/mobile_web_apps

**Comment by ianand** [comment]
@gr2m there's a deeper thing going on here. traditionally we often talk about websites having a frontend and backend but the front-end is really beholden to the backend. we're trying to liberate front-end developers, even when there is an existing backend in their infrastructure. to get a better understanding I'd recommend watching this webinar from the creator of HAML / Sass ( http://www.moovweb.com/mkt/webinar/interface_revolution_is_here_webinar_recording )

**Comment by gr2m** [comment]
I've created an account and looked into it. I don't think it makes a good fit, but only at the moment. Please be patient, I'm still setting things up. Currently I focus on systems that simply extend the JavaScript API with things like `signUp(username, password)` or `sendEmail(options)`, so I don't have to learn anything new as a frontend developer. 

When I understand Moovweb correctly, it tries to fix the problem of generating native user interfaces across plattforms, using an own syntax (*.ts) files. Which is great, it means I have one code base for current and future plattforms, right? But it's not the problem we try to solve here, we really try to focus to abstract away the problem that frontend developers want to build apps with their skills they already have. And to empower them to do that, we want to list solutions that provide APIs in the language they are familiar with, that abstract away the complexity of backends.

Does that make sense?

Still I think it's a great project and it somewhat goes in the same direction. I'd suggest we keep the pull request open and get back to it, once we have a better documentation of what we aim to do and a better process of adding new solutions. I hope that's all right?

**Comment by ptrikutam** [comment]
@gr2m Thanks for the detailed analysis. We completely understand the motivation behind noBackend.org now, and we still feel our platform could be a great asset for front end developers to use the skills they already know to create applications-- we've done it a number of times for our customers, and we really believe in the ease of use.

That being said, your points are correct. A key component to Moovweb's SDK is using Tritium files (*.ts) and though incredibly simple (I picked it up in about 2 days), it does have a small learning curve. We're working to make that smaller, and are in the process of putting together some guides & documentation geared towards making native / hybrid applications using our platform.

Your suggestion works, let's revisit this in the near future once both Moovweb's SDK and noBackend.org have matured a bit. Thanks for taking the time to look through everything!

**Pull request closed without merging**
