### PR TITLE
Update solutions.html

### PR DESCRIPTION
**Pull request by olistamplay**
Added Stamplay to the list

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks! Do you think you could implement the example app using Stamplay as its backend? I'd love to get this going again, I'd be also up to make another example app. Think todomvc, but for backends. Thoughts?

**Comment by olistamplay** [comment]
Hey Gregor.

Sounds good to me! Let me confirm that internally and see what we can do :)

I'll get back to you shortly.

Best regards,
Oli

**Comment by olistamplay** [comment]
Hey Gregor, hope you're well.

We're going to do something. It's in our production queue :)

I'll let you know once we've put something together.

Best regards,

**Comment by gr2m** [comment]
cool, looking forward to it :v:

**Pull request merged**
