### PR TITLE
New Article: Getting Started with noBackend

### PR DESCRIPTION
**Pull request by HipsterBrown**
I got the chance to talk about getting started with noBackend/Static/Front-End Driven apps at a local meetup, so I wanted to share my insight from the event and how best to get started. I am open for suggestions about editing the article or adding any more content.

### CODE REVIEW

**Comment by gr2m** [comment]
Nick, I'm sorry to let you wait that long, I'm still traveling until Tuesday and will have a look at it then. Thanks so much for the submit!!—
Gregor Martynus

**Comment by HipsterBrown** [comment]
Sounds great, Gregor! I look forward to hearing what you think.

**Comment by HipsterBrown** [comment]
Damn, didn't mean to close that, accident.

**Comment by gr2m** [comment]
it's fantastic, thanks so much for your contribution, I'm looking forward to see the app! Maybe we can list it on examples as well?

**Comment by HipsterBrown** [comment]
Maybe I'll use the new Firebase hosting just to post it up for people to play with & try out the Nodejitsu deployment from the hoodie-cli. :)

**Comment by gr2m** [comment]
Let me know if you have trouble with deployment, we can help. We had lots of trouble with Nodejitsu ourselves, and hope to ship our own free Hoodie hosting soon.

**Comment by HipsterBrown** [comment]
Thanks! I'm happy that Neighborhoodies Software is a reality now and can't wait to see it grow. HOODIE 4 Life.

**Pull request merged**
